### ISSUE TITLE
Como: usuario quiero ver el catalogo de ofertas y de solicitudes

### ISSUE THREAD

**Issue by IsabelUrribarri** [4GeeksAcademy/jire-final-project#2]

**Comment by ramicorrea21** [comment]
- [ ] Tabla ofertas (titulo, descripción, ubicación, imagen)
- [ ] Tabla solicitud (titulo, descripción, ubicación, imagen)
- [ ] Endpoint get ofertas 
- [ ] Endpoint get solicitudes

- [ ] vista catalogo de ofertas (cards)
- [ ] vista catalogo de solicitud (cards)
